web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ../.:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  build:
    ./php
  volumes:
    - ../.:/var/www/classroom
  links:
    - mysql
mysql:
  image: mysql
  ports:
    - "13306:3306"
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - /opt/mysql_data:/var/lib/mysql